backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    create: true
    folder: "content/pages"
    fields: 
    - {label: "Title", name: "title" , widget: "string"}
    - {label: "Img",  name: "image", widget: "image"}
    
        