backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
extension: json
format: json
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Portfolio"
      name: "portfolio"
      file: "content/portfolio.json"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Photos'
          name: "photos"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Tag", name: "tag", widget: "select", options: ['mariage', 'grossesse', 'bébé', 'famille', 'baptême', 'couple', 'portrait']}
            - { label: "Alt", name: "alt", widget: "text"}
            - { label: "Image", name: "image", widget: "image"}
            
    - label: "Prestations"
      name: "prestations"
      file: "content/prestations.json"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - label: 'Prestations'
          name: 'prestations'
          widget: list 
          fields: 
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Id", name: "id", widget: "string"}
            - { label: "Description", name: "description", widget: "text"} 
            - { label: "Price", name: "price", widget: "number"}

    - label: "Contact"
      name: "contact"
      file: "content/contact.json"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - label: 'Champs de formulaire'
          name: 'champs de formulaire'
          widget: list
          fields:
            - {label: "Name", name: "name", widget: "string"}
            - {label: "Type", name: "type", widget: "select", options: ['text', 'text-area', 'email']}
            - {label: "Placeholder", name: "placeholder", widget: "string"}



         
    
        