backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
extension: 'json'
format: 'json'
collections:
  - label: "Portfolio"
    name: portfolio
    files:  
      - label: "Photos"
        name: photos
        file: "../../content/portfolio/photos.json"
        fields:
          - label: "Liste des photos"
            name: liste des photos
            widget: list
            fields:
              - {label: "Title", name: title, widget: string}
              - {label: "Tag", name: tag, widget: string}
              - {label: 'Image', name: image, widget: image}





         
    
        