backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
extension: 'json'
format: 'json'
collections:
  - name: "pages"
    label: "Pages"
    create: true
    folder: "content/pages"
    files:
      - label: "Photos"
        name: 'photos'
        folder: 'content/pages'
        file: 'content/pages/photos.json'
        create: true
        fields: 
          - {label: "Title", name: "title" , widget: "string"}
          - {label: "Img",  name: "image", widget: "image"}
    
        