backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
extension: json
format: json
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Portfolio"
      name: "portfolio"
      file: "content/portfolio.json"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: 'Photos'
          name: "photos"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Tag", name: "tag", widget: "select",
                options: {
                  - { label: "Mariage", value: "mariage"}
                  - { label: "Grossesse", value: "grossesse"}
                  - { label: "Bébé", value: "bébé"}
                  - { label: "Famille", value: "famille"}
                  - { label: "Baptême", value: "baptême"}
                  - { label: "Couple", value: "couple"}
                }
              }
            - { label: "Alt", name: "alt", widget: "text"}
            - { label: "Image", name: "image", widget: "image"}
            - { label: "Width", name: "width", widget: "number"}
            - { label: "Height", name: "height", widget: "number"}





         
    
        